### ISSUE TITLE
APL presentation layer missing in iApp

### ISSUE THREAD

**Issue by tkam8** [f5devcentral/f5-tmsh2iapp#1]
##### ISSUE TYPE

 - Bug

##### tmsh2iapp version

```
20170802.2

```

##### BIGIP VERSION

```
[root@localhost:Active:Standalone] config # tmsh show sys version

Sys::Version
Main Package
  Product     BIG-IP
  Version     12.1.1
  Build       2.0.204
  Edition     Hotfix HF2
  Date        Fri Oct 21 17:35:48 PDT 2016
```

##### SUMMARY

My t2i file doesn't seem to have the correct variables for later use in the presentation layer of the iapp. Therefore, I do not see any configuration items when trying to create an application service.  Pls let me know if I am doing anything wrong. 

##### EXPECTED RESULTS

Something like below at the top of my t2i file. 

```
@label(__vs_address__): Address used for the HTTP and HTTPS virtual servers
@apl(__vs_address__): display "large" validator "IpAddress"
@label(__pm__apache_servers_for_http__): Apache servers for HTTP
@label(__pm__apache_servers_for_https__): Apache servers for HTTPS
```

##### ACTUAL RESULTS
```
ltm node 10.10.10.10 {
    address 10.10.10.10
}
ltm pool tmsh2iapp-pool1 {
    members {
        10.10.10.10:80 {
            address 10.10.10.10
        }
    }
}
ltm virtual vs1 {
    destination 10.1.1.100:80
    ip-protocol tcp
    mask 255.255.255.255
    pool tmsh2iapp-pool1
    profiles {
        tcp { }
    }
    source 0.0.0.0/0
    translate-address enabled
    translate-port enabled
}
ltm virtual-address 10.1.1.100 {
    address 10.1.1.100
    arp enabled
    icmp-echo enabled
    mask 255.255.255.255
    traffic-group traffic-group-1
}

```

##### REPRO STEPS

1. Configure BIG-IP via setup wizard. 
2. Create snapshot of base
```
[root@localhost:Active:Standalone] tmp # ./tmsh2iapp.pl snapshot-create try2-base
```
3. Configure BIG-IP with pool and vs for test
4. Create snapshot after config of L4-7 objects
```
[root@tmsh2iapptest:Active:Standalone] tmp # ./tmsh2iapp.pl snapshot-create try2-vspool
```
5. Create t2i file
```
[root@tmsh2iapptest:Active:Standalone] tmp # ./tmsh2iapp.pl t2i-create try2-base try2-vspool
Written the resulting baseline file to /var/tmp/tmsh2iapp-try2-base-try2-vspool.t2i

```

6. Create service
```
[root@tmsh2iapptest:Active:Standalone] tmp # ./tmsh2iapp.pl service tmsh2iapp-try2-base-try2-vspool.t2i 
Written the resulting iApp to tmsh2iapp-try2-base-try2-vspool.tmpl
```

7. Confirm all files

**Comment by tkam8** [comment]
[tmsh2iapp-try2.zip](https://github.com/f5devcentral/f5-tmsh2iapp/files/1233807/tmsh2iapp-try2.zip)

**Comment by alonsocamaro** [comment]
Hi Terence

tmsh2iapp is producing the expected .t2i baseline file. t2i-create creates a baseline .t2i that needs to be modified. tmsh2iapp cannot guess which items you want to have as parameters, you have to indicate them. Please see [t2i syntax page](https://github.com/f5devcentral/f5-tmsh2iapp/wiki/t2i-syntax) page for details. Note that you will have to remove some elements too.

Please let me know if you have any doubt

Regards

            Ulises

**Comment by tkam8** [comment]
Got it, thanks!
