### ISSUE TITLE
[Wiki] minor fixes

### ISSUE THREAD

**Issue by tkam8** [f5devcentral/f5-tmsh2iapp#2]
Noticed some typos in the wiki. Looks like a different .git so sending my fixes via my own repo. 

https://github.com/tkam8/tmsh2iApp-kamwiki/commit/8ad37f8bb5120c7e369a7f6e2c9e9d472314c41e

https://github.com/tkam8/tmsh2iApp-kamwiki/commit/de2a933b0a7798396cceef56b89dcce39b37c8ca

https://github.com/tkam8/tmsh2iApp-kamwiki/commit/3ab3dce1c009ba89d04939a0e3c36e88ad4fbc52

Let me know if any questions

**Comment by alonsocamaro** [comment]
Many thanks Terence! Just applied the typos that you spotted.

Best regards

       Ulises
